INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("1", "Stench", "By releasing stench when attacking, this Pokémon may cause the target to flinch.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("2", "Drizzle", "The Pokémon makes it rain when it enters a battle.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("3", "Speed Boost", "Its Speed stat is boosted every turn.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("4", "Battle Armor", "Hard armor protects the Pokémon from critical hits.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("5", "Sturdy", "It cannot be knocked out with one hit. One-hit KO moves cannot knock it out, either.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("6", "Damp", "Prevents the use of explosive moves such as Self-Destruct by dampening its surroundings.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("7", "Limber", "Its limber body protects the Pokémon from paralysis.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("8", "Sand Veil", "Boosts the Pokémon’s evasion in a sandstorm.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("9", "Static", "The Pokémon is charged with static electricity, so contact with it may cause paralysis.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("10", "Volt Absorb", "Restores HP if hit by an Electric-type move, instead of taking damage.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("11", "Water Absorb", "Restores HP if hit by a Water-type move, instead of taking damage.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("12", "Oblivious", "The Pokémon is oblivious, and that keeps it from being infatuated or falling for taunts.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("13", "Cloud Nine", "Eliminates the effects of weather.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("14", "Compound Eyes", "The Pokémon’s compound eyes boost its accuracy.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("15", "Insomnia", "The Pokémon is suffering from insomnia and cannot fall asleep.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("16", "Color Change", "The Pokémon’s type becomes the type of the move used on it.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("17", "Immunity", "The immune system of the Pokémon prevents it from getting poisoned.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("18", "Flash Fire", "Powers up the Pokémon’s Fire-type moves if it’s hit by one.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("19", "Shield Dust", "This Pokémon’s dust blocks the additional effects of attacks taken.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("20", "Own Tempo", "This Pokémon has its own tempo, and that prevents it from becoming confused.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("21", "Suction Cups", "This Pokémon uses suction cups to stay in one spot to negate all moves and items that force switching out.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("22", "Intimidate", "The Pokémon intimidates opposing Pokémon upon entering battle, lowering their Attack stat.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("23", "Shadow Tag", "This Pokémon steps on the opposing Pokémon’s shadow to prevent it from escaping.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("24", "Rough Skin", "This Pokémon inflicts damage with its rough skin to the attacker on contact.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("25", "Wonder Guard", "Its mysterious power only lets supereffective moves hit the Pokémon.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("26", "Levitate", "By floating in the air, the Pokémon receives full immunity to all Ground-type moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("27", "Effect Spore", "Contact with the Pokémon may inflict poison, sleep, or paralysis on its attacker.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("28", "Synchronize", "The attacker will receive the same status condition if it inflicts a burn, poison, or paralysis to the Pokémon.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("29", "Clear Body", "Prevents other Pokémon’s moves or Abilities from lowering the Pokémon’s stats.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("30", "Natural Cure", "All status conditions heal when the Pokémon switches out.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("31", "Lightning Rod", "The Pokémon draws in all Electric-type moves.  Instead of being hit by Electric-type moves,  it boosts its Sp. Atk.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("32", "Serene Grace", "Boosts the likelihood of additional effects occurring  when attacking.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("33", "Swift Swim", "Boosts the Pokémon’s Speed stat in rain.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("34", "Chlorophyll", "Boosts the Pokémon’s Speed stat in harsh sunlight.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("35", "Illuminate", "Raises the likelihood of meeting wild Pokémon by illuminating the surroundings.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("36", "Trace", "When it enters a battle, the Pokémon copies an opposing Pokémon’s Ability.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("37", "Huge Power", "Doubles the Pokémon’s Attack stat.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("38", "Poison Point", "Contact with the Pokémon may poison the attacker.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("39", "Inner Focus", "The Pokémon’s intensely focused, and that protects the Pokémon from flinching.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("40", "Magma Armor", "The Pokémon is covered with hot magma, which prevents the Pokémon from becoming frozen.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("41", "Water Veil", "The Pokémon is covered with a water veil, which prevents the Pokémon from getting a burn.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("42", "Magnet Pull", "Prevents Steel-type Pokémon from escaping using its magnetic force.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("43", "Soundproof", "Soundproofing of the Pokémon itself gives full  immunity to all sound-based moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("44", "Rain Dish", "The Pokémon gradually regains HP in rain.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("45", "Sand Stream", "The Pokémon summons a sandstorm when it enters a battle.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("46", "Pressure", "By putting pressure on the opposing Pokémon, it raises their PP usage.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("47", "Thick Fat", "The Pokémon is protected by a layer of thick fat, which halves the damage taken from Fire- and Ice-type moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("48", "Early Bird", "The Pokémon awakens twice as fast as other Pokémon from sleep.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("49", "Flame Body", "Contact with the Pokémon may burn the attacker.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("50", "Run Away", "Enables a sure getaway from wild Pokémon.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("51", "Keen Eye", "Keen eyes prevent other Pokémon from lowering this Pokémon’s accuracy.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("52", "Hyper Cutter", "The Pokémon’s proud of its powerful pincers. They prevent other Pokémon from lowering its Attack stat.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("53", "Pickup", "The Pokémon may pick up the item an opposing Pokémon used during a battle. It may pick up items outside of battle, too.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("54", "Truant", "The Pokémon can’t use a move the following turn if it uses one.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("55", "Hustle", "Boosts the Attack stat, but lowers accuracy.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("56", "Cute Charm", "Contact with the Pokémon may cause infatuation.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("57", "Plus", "Boosts the Sp. Atk stat of the Pokémon if an ally with the Plus or Minus Ability is also in battle.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("58", "Minus", "Boosts the Sp. Atk stat of the Pokémon if an ally with the Plus or Minus Ability is also in battle.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("59", "Forecast", "The Pokémon transforms with the weather to change its type to Water, Fire, or Ice.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("60", "Sticky Hold", "Items held by the Pokémon are stuck fast and cannot be removed by other Pokémon.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("61", "Shed Skin", "The Pokémon may heal its own status conditions by shedding its skin.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("62", "Guts", "It’s so gutsy that having a status condition boosts the Pokémon’s Attack stat.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("63", "Marvel Scale", "The Pokémon’s marvelous scales boost the Defense stat if it has a status condition.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("64", "Liquid Ooze", "Oozed liquid has strong stench, which damages attackers using any draining move.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("65", "Overgrow", "Powers up Grass-type moves when the Pokémon’s HP is low.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("66", "Blaze", "Powers up Fire-type moves when the Pokémon’s HP is low.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("67", "Torrent", "Powers up Water-type moves when the Pokémon’s HP is low.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("68", "Swarm", "Powers up Bug-type moves when the Pokémon’s HP is low.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("69", "Rock Head", "Protects the Pokémon from recoil damage.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("70", "Drought", "Turns the sunlight harsh when the Pokémon enters a battle.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("71", "Arena Trap", "Prevents opposing Pokémon from fleeing.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("72", "Vital Spirit", "The Pokémon is full of vitality, and that prevents it from falling asleep.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("73", "White Smoke", "The Pokémon is protected by its white smoke, which prevents other Pokémon from lowering its stats.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("74", "Pure Power", "Using its pure power, the Pokémon doubles its Attack stat.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("75", "Shell Armor", "A hard shell protects the Pokémon from critical hits.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("76", "Air Lock", "Eliminates the effects of weather.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("77", "Tangled Feet", "Raises evasion if the Pokémon is confused.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("78", "Motor Drive", "Boosts its Speed stat if hit by an Electric-type move, instead of taking damage.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("79", "Rivalry", "Becomes competitive and deals more damage to Pokémon of the same gender, but deals less to Pokémon of the opposite gender.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("80", "Steadfast", "The Pokémon’s determination boosts the Speed stat each time the Pokémon flinches.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("81", "Snow Cloak", "Boosts evasion in a hailstorm.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("82", "Gluttony", "Makes the Pokémon eat a held Berry when its HP drops to half or less, which is sooner than usual.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("83", "Anger Point", "The Pokémon is angered when it takes a critical hit, and that maxes its Attack stat.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("84", "Unburden", "Boosts the Speed stat if the Pokémon’s held item is  used or lost.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("85", "Heatproof", "The heatproof body of the Pokémon halves the damage from Fire-type moves that hit it.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("86", "Simple", "The stat changes the Pokémon receives are doubled.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("87", "Dry Skin", "Restores HP in rain or when hit by Water-type moves. Reduces HP in harsh sunlight, and increases the damage received from Fire-type moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("88", "Download", "Compares an opposing Pokémon’s Defense and Sp. Def stats before raising its own Attack or Sp. Atk stat—whichever will be more effective.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("89", "Iron Fist", "Powers up punching moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("90", "Poison Heal", "Restores HP if the Pokémon is poisoned, instead of losing HP.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("91", "Adaptability", "Powers up moves of the same type as the Pokémon.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("92", "Skill Link", "Maximizes the number of times multi-strike moves hit.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("93", "Hydration", "Heals status conditions if it’s raining.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("94", "Solar Power", "Boosts the Sp. Atk stat in harsh sunlight, but HP decreases every turn.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("95", "Quick Feet", "Boosts the Speed stat if the Pokémon has a status condition.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("96", "Normalize", "All the Pokémon’s moves become Normal type. The power of those moves is boosted a little.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("97", "Sniper", "Powers up moves if they become critical hits when attacking.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("98", "Magic Guard", "The Pokémon only takes damage from attacks.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("99", "No Guard", "The Pokémon employs no-guard tactics to ensure incoming and outgoing attacks always land.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("100", "Stall", "The Pokémon moves after all other Pokémon do.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("101", "Technician", "Powers up the Pokémon’s weaker moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("102", "Leaf Guard", "Prevents status conditions in harsh sunlight.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("103", "Klutz", "The Pokémon can’t use any held items.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("104", "Mold Breaker", "Moves can be used on the target regardless of its Abilities.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("105", "Super Luck", "The Pokémon is so lucky that the critical-hit ratios of its moves are boosted.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("106", "Aftermath", "Damages the attacker if it contacts the Pokémon with a finishing hit.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("107", "Anticipation", "The Pokémon can sense an opposing Pokémon’s dangerous moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("108", "Forewarn", "When it enters a battle, the Pokémon can tell one of the moves an opposing Pokémon has.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("109", "Unaware", "When attacking, the Pokémon ignores the target Pokémon’s stat changes.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("110", "Tinted Lens", "The Pokémon can use “not very effective” moves to deal regular damage. ")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("111", "Filter", "Reduces the power of supereffective attacks taken.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("112", "Slow Start", "For five turns, the Pokémon’s Attack and Speed stats are halved.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("113", "Scrappy", "The Pokémon can hit Ghost-type Pokémon with Normal- and Fighting-type moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("114", "Storm Drain", "Draws in all Water-type moves. Instead of being hit  by Water-type moves, it boosts its Sp. Atk.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("115", "Ice Body", "The Pokémon gradually regains HP in a hailstorm.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("116", "Solid Rock", "Reduces the power of supereffective attacks taken.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("117", "Snow Warning", "The Pokémon summons a hailstorm when it enters a battle.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("118", "Honey Gather", "The Pokémon may gather Honey after a battle.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("119", "Frisk", "When it enters a battle, the Pokémon can check an opposing Pokémon’s held item.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("120", "Reckless", "Powers up moves that have recoil damage.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("121", "Multitype", "Changes the Pokémon’s type to match the Plate or Z-Crystal it holds.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("122", "Flower Gift", "Boosts the Attack and Sp. Def stats of itself and allies in harsh sunlight.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("123", "Bad Dreams", "Reduces the HP of sleeping opposing Pokémon.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("124", "Pickpocket", "Steals an item from an attacker that made direct contact.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("125", "Sheer Force", "Removes additional effects to increase the power of moves when attacking.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("126", "Contrary", "Makes stat changes have an opposite effect.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("127", "Unnerve", "Unnerves opposing Pokémon and makes them unable to eat Berries.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("128", "Defiant", "Boosts the Pokémon’s Attack stat sharply when its stats are lowered.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("129", "Defeatist", "Halves the Pokémon’s Attack and Sp. Atk stats when its HP becomes half or less.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("130", "Cursed Body", "May disable a move used on the Pokémon.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("131", "Healer", "Sometimes heals an ally’s status condition.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("132", "Friend Guard", "Reduces damage done to allies.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("133", "Weak Armor", "Physical attacks to the Pokémon lower its Defense stat but sharply raise its Speed stat.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("134", "Heavy Metal", "Doubles the Pokémon’s weight.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("135", "Light Metal", "Halves the Pokémon’s weight.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("136", "Multiscale", "Reduces the amount of damage the Pokémon takes when its HP is full.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("137", "Toxic Boost", "Powers up physical attacks when the Pokémon is poisoned.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("138", "Flare Boost", "Powers up special attacks when the Pokémon is burned.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("139", "Harvest", "May create another Berry after one is used.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("140", "Telepathy", "Anticipates an ally’s attack and dodges it.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("141", "Moody", "Raises one stat sharply and lowers another every turn.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("142", "Overcoat", "Protects the Pokémon from things like sand, hail, and powder.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("143", "Poison Touch", "May poison a target when the Pokémon makes contact.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("144", "Regenerator", "Restores a little HP when withdrawn from battle.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("145", "Big Pecks", "Protects the Pokémon from Defense-lowering effects.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("146", "Sand Rush", "Boosts the Pokémon’s Speed stat in a sandstorm.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("147", "Wonder Skin", "Makes status moves more likely to miss.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("148", "Analytic", "Boosts move power when the Pokémon moves last.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("149", "Illusion", "Comes out disguised as the Pokémon in the party’s last spot.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("150", "Imposter", "The Pokémon transforms itself into the Pokémon it’s facing.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("151", "Infiltrator", "Passes through the opposing Pokémon’s barrier, substitute, and the like and strikes.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("152", "Mummy", "Contact with the Pokémon changes the attacker’s Ability to Mummy.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("153", "Moxie", "The Pokémon shows moxie, and that boosts the Attack stat after knocking out any Pokémon.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("154", "Justified", "Being hit by a Dark-type move boosts the Attack stat of the Pokémon, for justice.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("155", "Rattled", "Dark-, Ghost-, and Bug-type moves scare the Pokémon and boost its Speed stat.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("156", "Magic Bounce", "Reflects status moves, instead of getting hit by them.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("157", "Sap Sipper", "Boosts the Attack stat if hit by a Grass-type move, instead of taking damage.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("158", "Prankster", "Gives priority to a status move.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("159", "Sand Force", "Boosts the power of Rock-, Ground-, and Steel-type moves in a sandstorm.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("160", "Iron Barbs", "Inflicts damage to the attacker on contact with iron barbs.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("161", "Zen Mode", "Changes the Pokémon’s shape when HP is half or less.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("162", "Victory Star", "Boosts the accuracy of its allies and itself.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("163", "Turboblaze", "Moves can be used on the target regardless of its Abilities.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("164", "Teravolt", "Moves can be used on the target regardless of its Abilities.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("165", "Aroma Veil", "Protects itself and its allies from attacks that limit their move choices.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("166", "Flower Veil", "Ally Grass-type Pokémon are protected from status conditions and the lowering of their stats.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("167", "Cheek Pouch", "Restores HP as well when the Pokémon eats a Berry.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("168", "Protean", "Changes the Pokémon’s type to the type of the move it’s about to use.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("169", "Fur Coat", "Halves the damage from physical moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("170", "Magician", "The Pokémon steals the held item of a Pokémon it hits with a move.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("171", "Bulletproof", "Protects the Pokémon from some ball and bomb moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("172", "Competitive", "Boosts the Sp. Atk stat sharply when a stat is lowered.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("173", "Strong Jaw", "The Pokémon’s strong jaw boosts the power of its biting moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("174", "Refrigerate", "Normal-type moves become Ice-type moves. The power of those moves is boosted a little.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("175", "Sweet Veil", "Prevents itself and ally Pokémon from falling asleep.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("176", "Stance Change", "The Pokémon changes its form to Blade Forme when it uses an attack move, and changes to Shield Forme when it uses King’s Shield.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("177", "Gale Wings", "Gives priority to Flying-type moves when the  Pokémon’s HP is full.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("178", "Mega Launcher", "Powers up aura and pulse moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("179", "Grass Pelt", "Boosts the Pokémon’s Defense stat in  Grassy Terrain.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("180", "Symbiosis", "The Pokémon passes its item to an ally that has used up an item.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("181", "Tough Claws", "Powers up moves that make direct contact.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("182", "Pixilate", "Normal-type moves become Fairy-type moves. The power of those moves is boosted a little.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("183", "Gooey", "Contact with the Pokémon lowers the attacker’s Speed stat.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("184", "Aerilate", "Normal-type moves become Flying-type moves. The power of those moves is boosted a little.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("185", "Parental Bond", "Parent and child each attacks.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("186", "Dark Aura", "Powers up each Pokémon’s Dark-type moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("187", "Fairy Aura", "Powers up each Pokémon’s Fairy-type moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("188", "Aura Break", "The effects of “Aura” Abilities are reversed to lower the power of affected moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("189", "Primordial Sea", "The Pokémon changes the weather to nullify Fire-type attacks.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("190", "Desolate Land", "The Pokémon changes the weather to nullify Water-type attacks.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("191", "Delta Stream", "The Pokémon changes the weather to eliminate all of the Flying type’s weaknesses.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("192", "Stamina", "Boosts the Defense stat when hit by an attack.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("193", "Wimp Out", "The Pokémon cowardly switches out when its HP becomes half or less.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("194", "Emergency Exit", "The Pokémon, sensing danger, switches out when its HP becomes half or less.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("195", "Water Compaction", "Boosts the Pokémon’s Defense stat sharply when hit by a Water-type move.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("196", "Merciless", "The Pokémon’s attacks become critical hits if the target is poisoned.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("197", "Shields Down", "When its HP becomes half or less, the Pokémon’s shell breaks and it becomes aggressive.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("198", "Stakeout", "Doubles the damage dealt to the target’s replacement if the target switches out.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("199", "Water Bubble", "Lowers the power of Fire-type moves done to the Pokémon and prevents the Pokémon from getting a burn.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("200", "Steelworker", "Powers up Steel-type moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("201", "Berserk", "Boosts the Pokémon’s Sp. Atk stat when it takes a  hit that causes its HP to become half or less.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("202", "Slush Rush", "Boosts the Pokémon’s Speed stat in a hailstorm.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("203", "Long Reach", "The Pokémon uses its moves without making contact with the target.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("204", "Liquid Voice", "All sound-based moves become Water-type moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("205", "Triage", "Gives priority to a healing move.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("206", "Galvanize", "Normal-type moves become Electric-type moves. The power of those moves is boosted a little.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("207", "Surge Surfer", "Doubles the Pokémon’s Speed stat on Electric Terrain.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("208", "Schooling", "When it has a lot of HP, the Pokémon forms a powerful school. It stops schooling when its HP is low.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("209", "Disguise", "Once per battle, the shroud that covers the Pokémon can protect it from an attack.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("210", "Battle Bond", "Defeating an opposing Pokémon strengthens the Pokémon’s bond with its Trainer, and it becomes Ash-Greninja. Water Shuriken gets more powerful.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("211", "Power Construct", "Other Cells gather to aid when its HP becomes half or less. Then the Pokémon changes its form to Complete Forme.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("212", "Corrosion", "The Pokémon can poison the target even if it’s a Steel or Poison type.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("213", "Comatose", "It’s always drowsing and will never wake up. It can attack without waking up.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("214", "Queenly Majesty", "Its majesty pressures the opposing Pokémon, making it unable to attack using priority moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("215", "Innards Out", "Damages the attacker landing the finishing hit by the amount equal to its last HP.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("216", "Dancer", "When another Pokémon uses a dance move, it can use a dance move following it regardless of its Speed.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("217", "Battery", "Powers up ally Pokémon’s special moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("218", "Fluffy", "Halves the damage taken from moves that make direct contact, but doubles that of Fire-type moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("219", "Dazzling", "Surprises the opposing Pokémon, making it unable to attack using priority moves.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("220", "Soul-Heart", "Boosts its Sp. Atk stat every time a Pokémon faints.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("221", "Tangling Hair", "Contact with the Pokémon lowers the attacker’s Speed stat.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("222", "Receiver", "The Pokémon copies the Ability of a defeated ally.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("223", "Power of Alchemy", "The Pokémon copies the Ability of a defeated ally.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("224", "Beast Boost", "The Pokémon boosts its most proficient stat each time it knocks out a Pokémon.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("225", "RKS System", "Changes the Pokémon’s type to match the memory disc it holds.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("226", "Electric Surge", "Turns the ground into Electric Terrain when the Pokémon enters a battle.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("227", "Psychic Surge", "Turns the ground into Psychic Terrain when the Pokémon enters a battle.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("228", "Misty Surge", "Turns the ground into Misty Terrain when the Pokémon enters a battle.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("229", "Grassy Surge", "Turns the ground into Grassy Terrain when the Pokémon enters a battle.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("230", "Full Metal Body", "Prevents other Pokémon’s moves or Abilities from lowering the Pokémon’s stats.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("231", "Shadow Shield", "Reduces the amount of damage the Pokémon takes while its HP is full.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("232", "Prism Armor", "Reduces the power of supereffective attacks taken.")
INSERT INTO Habilidade (id_habilidade, nome, descricao) VALUES ("233", "Neuroforce", "Powers up moves that are super effective.")
